### ISSUE TITLE
Quick question : why did you stop working on this?

### ISSUE THREAD

**Issue by DeceptedParasite** [DotWith/Friday-Night-Funkin#1]
if it's an obvious reason I'm sorry, but I'd still like to know

**Comment by DotWith** [comment]
It's not **r e a d y**....
It's not **r e a d y** child
:D

**Comment by DotWith** [comment]
Oh so this mod is old im remaking it on [Repo](https://github.com/the-rebellion-hideout/Dot-Engine)

**Comment by DeceptedParasite** [comment]
ah, alright thanks
